Repository ServerOpenMC/PluginV2, pull requests merged in 2024-11, with the labels that each got.

#2 Adding spawn system
  .gitignore
  src/main/java/fr/openmc/core/OMCPlugin.java
  src/main/java/fr/openmc/core/commands/CommandsManager.java
  src/main/java/fr/openmc/core/commands/fun/Playtime.java
  src/main/java/fr/openmc/core/commands/utils/SetSpawn.java
  src/main/java/fr/openmc/core/commands/utils/Socials.java
  src/main/java/fr/openmc/core/commands/utils/Spawn.java
  src/main/java/fr/openmc/core/features/utils/analytics/AnalyticsManager.java
  src/main/java/fr/openmc/core/features/utils/analytics/Stats.java
  src/main/java/fr/openmc/core/features/utils/spawn/SpawnManager.java
  src/main/java/fr/openmc/core/listeners/SessionsListener.java
  src/main/java/fr/openmc/core/utils/database/DatabaseManager.java
  src/main/java/fr/openmc/core/utils/messages/MessagesManager.java
  src/main/resources/data/spawn.yml
  src/main/resources/paper-plugin.yml
Labels: features

#5 Add Motd
  src/main/java/fr/openmc/core/OMCPlugin.java
  src/main/java/fr/openmc/core/utils/MotdUtils.java
  src/main/resources/data/motd.yml
  src/test/java/fr/openmc/core/utils/DateUtilsTests.java
  src/test/java/fr/openmc/core/utils/MotdUtilsTests.java
Labels: features

#6 Add Join and Quit Message
  build.gradle
  src/main/java/fr/openmc/core/OMCPlugin.java
  src/main/java/fr/openmc/core/commands/utils/SetSpawn.java
  src/main/java/fr/openmc/core/commands/utils/Spawn.java
  src/main/java/fr/openmc/core/listeners/JoinMessageListener.java
  src/main/java/fr/openmc/core/listeners/ListenersManager.java
  src/main/java/fr/openmc/core/listeners/QuitMessageListener.java
  src/main/java/fr/openmc/core/utils/LuckPermAPI.java
  src/main/java/fr/openmc/core/utils/MotdUtils.java
  src/main/resources/data/motd.yml
  src/main/resources/plugin.yml
  src/test/java/fr/openmc/core/utils/MotdUtilsTests.java
Labels: features

#7 [Feature] Adding economy sysem.
  build.gradle
  src/main/java/fr/openmc/core/OMCPlugin.java
  src/main/java/fr/openmc/core/commands/CommandsManager.java
  src/main/java/fr/openmc/core/commands/economy/Baltop.java
  src/main/java/fr/openmc/core/commands/economy/Money.java
  src/main/java/fr/openmc/core/features/utils/economy/EconomyData.java
  src/main/java/fr/openmc/core/features/utils/economy/EconomyManager.java
  src/main/java/fr/openmc/core/utils/database/DatabaseManager.java
  src/main/java/fr/openmc/core/utils/messages/MessagesManager.java
  src/main/resources/plugin.yml
Labels: features

#9 Add City base
  build.gradle
  src/main/java/fr/openmc/core/OMCPlugin.java
  src/main/java/fr/openmc/core/features/city/CityManager.java
  src/main/java/fr/openmc/core/features/city/CityMessages.java
  src/main/java/fr/openmc/core/features/city/CityUtils.java
  src/main/java/fr/openmc/core/features/city/commands/AdminCityCommands.java
  src/main/java/fr/openmc/core/features/city/commands/CityCommands.java
  src/main/java/fr/openmc/core/features/city/listeners/CityDoorsListener.java
  src/main/java/fr/openmc/core/features/utils/economy/EconomyManager.java
  src/main/java/fr/openmc/core/utils/customitems/CloseButton.java
  src/main/java/fr/openmc/core/utils/customitems/CustomItem.java
  src/main/java/fr/openmc/core/utils/customitems/NextPage.java
  src/main/java/fr/openmc/core/utils/customitems/PreviousPage.java
  src/main/java/fr/openmc/core/utils/database/DatabaseManager.java
  src/main/java/fr/openmc/core/utils/messages/Prefix.java
  src/main/resources/plugin.yml
Labels: enhancement, help wanted

#10 Nouvelle structure, Ajout des transactions
  src/main/java/fr/openmc/core/OMCPlugin.java
  src/main/java/fr/openmc/core/commands/CommandsManager.java
  src/main/java/fr/openmc/core/commands/utils/SetSpawn.java
  src/main/java/fr/openmc/core/commands/utils/Spawn.java
  src/main/java/fr/openmc/core/commands/utils/SpawnManager.java
  src/main/java/fr/openmc/core/features/analytics/AnalyticsManager.java
  src/main/java/fr/openmc/core/features/analytics/Stats.java
  src/main/java/fr/openmc/core/features/city/CityMessages.java
  src/main/java/fr/openmc/core/features/city/commands/AdminCityCommands.java
  src/main/java/fr/openmc/core/features/city/commands/CityCommands.java
  src/main/java/fr/openmc/core/features/economy/EconomyData.java
  src/main/java/fr/openmc/core/features/economy/EconomyManager.java
  src/main/java/fr/openmc/core/features/economy/Transaction.java
  src/main/java/fr/openmc/core/features/economy/TransactionsManager.java
  src/main/java/fr/openmc/core/features/economy/TransactionsMenu.java
  src/main/java/fr/openmc/core/features/economy/commands/Baltop.java
  src/main/java/fr/openmc/core/features/economy/commands/History.java
  src/main/java/fr/openmc/core/features/economy/commands/Money.java
  src/main/java/fr/openmc/core/features/economy/commands/Pay.java
  src/main/java/fr/openmc/core/listeners/SessionsListener.java
  src/main/java/fr/openmc/core/utils/database/DatabaseManager.java
  src/main/resources/config.yml
Labels: enhancement
