Repository ServerOpenMC/PluginV2, pull requests merged in 2025-05, with the labels that each got.

#362 Fix /omcrestart
  src/main/java/fr/openmc/core/commands/utils/Restart.java
  src/main/java/fr/openmc/core/features/city/commands/CityCommands.java
Labels: :sparkles: Fixes

#365 Fix failing test
  build.gradle
  src/main/java/fr/openmc/core/OMCPlugin.java
Labels: :sparkles: Fixes

#363 Amélioration de du verionning + Update `MessagesManager`
  src/main/java/fr/openmc/core/CommandsManager.java
  src/main/java/fr/openmc/core/ListenersManager.java
  src/main/java/fr/openmc/core/OMCPlugin.java
  src/main/java/fr/openmc/core/commands/utils/Restart.java
  src/main/java/fr/openmc/core/features/updates/UpdateCommand.java
  src/main/java/fr/openmc/core/features/updates/UpdateListener.java
  src/main/java/fr/openmc/core/features/updates/UpdateManager.java
  src/main/java/fr/openmc/core/listeners/JoinMessageListener.java
  src/main/java/fr/openmc/core/utils/messages/MessagesManager.java
Labels: 🆙 Amélioration

#371 Ajout de l'API MenuLib dans le projet
  build.gradle
  src/main/java/fr/openmc/api/menulib/Menu.java
  src/main/java/fr/openmc/api/menulib/MenuLib.java
  src/main/java/fr/openmc/api/menulib/PaginatedMenu.java
  src/main/java/fr/openmc/api/menulib/utils/InventorySize.java
  src/main/java/fr/openmc/api/menulib/utils/ItemBuilder.java
  src/main/java/fr/openmc/api/menulib/utils/ItemUtils.java
  src/main/java/fr/openmc/api/menulib/utils/StaticSlots.java
  src/main/java/fr/openmc/core/OMCPlugin.java
  src/main/java/fr/openmc/core/features/adminshop/AdminShopManager.java
  src/main/java/fr/openmc/core/features/adminshop/menus/AdminShopCategoryMenu.java
  src/main/java/fr/openmc/core/features/adminshop/menus/AdminShopMenu.java
  src/main/java/fr/openmc/core/features/adminshop/menus/ColorVariantsMenu.java
  src/main/java/fr/openmc/core/features/adminshop/menus/ConfirmMenu.java
  src/main/java/fr/openmc/core/features/city/menu/CityChunkMenu.java
  src/main/java/fr/openmc/core/features/city/menu/CityMenu.java
  src/main/java/fr/openmc/core/features/city/menu/CityModifyMenu.java
  src/main/java/fr/openmc/core/features/city/menu/CityTransferMenu.java
  src/main/java/fr/openmc/core/features/city/menu/CityTypeMenu.java
  src/main/java/fr/openmc/core/features/city/menu/InvitationsMenu.java
  src/main/java/fr/openmc/core/features/city/menu/NoCityMenu.java
  src/main/java/fr/openmc/core/features/city/menu/bank/CityBankDepositMenu.java
  src/main/java/fr/openmc/core/features/city/menu/bank/CityBankMenu.java
  src/main/java/fr/openmc/core/features/city/menu/bank/CityBankWithdrawMenu.java
  src/main/java/fr/openmc/core/features/city/menu/mascots/MascotMenu.java
  src/main/java/fr/openmc/core/features/city/menu/mascots/MascotsDeadMenu.java
  src/main/java/fr/openmc/core/features/city/menu/mascots/MascotsSkinMenu.java
  src/main/java/fr/openmc/core/features/city/menu/playerlist/CityPlayerGestionMenu.java
  src/main/java/fr/openmc/core/features/city/menu/playerlist/CityPlayerListMenu.java
  src/main/java/fr/openmc/core/features/contest/menu/ConfirmMenu.java
  src/main/java/fr/openmc/core/features/contest/menu/ContributionMenu.java
  src/main/java/fr/openmc/core/features/contest/menu/MoreInfoMenu.java
  src/main/java/fr/openmc/core/features/contest/menu/TradeMenu.java
  src/main/java/fr/openmc/core/features/contest/menu/VoteMenu.java
  src/main/java/fr/openmc/core/features/economy/TransactionsMenu.java
  src/main/java/fr/openmc/core/features/economy/menu/PersonalBankDepositMenu.java
  src/main/java/fr/openmc/core/features/economy/menu/PersonalBankMenu.java
  src/main/java/fr/openmc/core/features/economy/menu/PersonalBankWithdrawMenu.java
  src/main/java/fr/openmc/core/features/homes/command/TpHome.java
  src/main/java/fr/openmc/core/features/homes/menu/HomeChangeIconMenu.java
  src/main/java/fr/openmc/core/features/homes/menu/HomeConfigMenu.java
  src/main/java/fr/openmc/core/features/homes/menu/HomeDeleteConfirmMenu.java
  src/main/java/fr/openmc/core/features/homes/menu/HomeMenu.java
  src/main/java/fr/openmc/core/features/homes/menu/HomeUpgradeMenu.java
  src/main/java/fr/openmc/core/features/quests/menus/QuestsMenu.java
  src/main/java/fr/openmc/core/utils/menu/ConfirmMenu.java
  src/main/java/fr/openmc/core/utils/menu/MenuUtils.java
Labels: :package: Features

#366 Ajout du '/city list'
  src/main/java/fr/openmc/core/features/city/CityManager.java
  src/main/java/fr/openmc/core/features/city/commands/CityCommands.java
  src/main/java/fr/openmc/core/features/city/conditions/CityInviteConditions.java
  src/main/java/fr/openmc/core/features/city/mascots/MascotUtils.java
  src/main/java/fr/openmc/core/features/city/menu/CityMenu.java
  src/main/java/fr/openmc/core/features/city/menu/bank/CityBankDepositMenu.java
  src/main/java/fr/openmc/core/features/city/menu/list/CityListDetailsMenu.java
  src/main/java/fr/openmc/core/features/city/menu/list/CityListMenu.java
  src/main/java/fr/openmc/core/features/scoreboards/ScoreboardManager.java
  src/main/java/fr/openmc/core/utils/PlayerUtils.java
Labels: :package: Features

#373 Ajoute SignGUI en 1.21.5
  README.md
  build.gradle
  src/main/java/fr/openmc/api/signgui/SignEditor.java
  src/main/java/fr/openmc/api/signgui/SignGUI.java
  src/main/java/fr/openmc/api/signgui/SignGUIAction.java
  src/main/java/fr/openmc/api/signgui/SignGUIBuilder.java
  src/main/java/fr/openmc/api/signgui/SignGUIChannelHandler.java
  src/main/java/fr/openmc/api/signgui/SignGUIFinishHandler.java
  src/main/java/fr/openmc/api/signgui/SignGUIResult.java
  src/main/java/fr/openmc/api/signgui/exception/SignGUIException.java
  src/main/java/fr/openmc/api/signgui/exception/SignGUIVersionException.java
  src/main/java/fr/openmc/api/signgui/wrapper/MojangWrapper.java
  src/main/java/fr/openmc/core/features/city/menu/CityModifyMenu.java
  src/main/java/fr/openmc/core/features/city/menu/NoCityMenu.java
  src/main/java/fr/openmc/core/features/city/menu/bank/CityBankDepositMenu.java
  src/main/java/fr/openmc/core/features/city/menu/bank/CityBankWithdrawMenu.java
  src/main/java/fr/openmc/core/features/city/menu/playerlist/CityPlayerListMenu.java
  src/main/java/fr/openmc/core/features/economy/menu/PersonalBankDepositMenu.java
  src/main/java/fr/openmc/core/features/economy/menu/PersonalBankWithdrawMenu.java
  third_party_licenses/SignGUI_LICENSE
Labels: :package: Features, :sparkles: Fixes

#374 Ajout de l'affichage de la durée avant le prochaine intérêt
  src/main/java/fr/openmc/core/features/city/menu/bank/CityBankMenu.java
  src/main/java/fr/openmc/core/features/economy/BankManager.java
  src/main/java/fr/openmc/core/features/economy/menu/PersonalBankMenu.java
  src/main/java/fr/openmc/core/utils/DateUtils.java
Labels: :arrows_counterclockwise: Changement

#379 Format city balance display using simplified number representation.
  src/main/java/fr/openmc/core/features/city/menu/list/CityListDetailsMenu.java
  src/main/java/fr/openmc/core/features/city/menu/list/CityListMenu.java
Labels: :sparkles: Fixes

#385 Reformatage du death message
  src/main/java/fr/openmc/core/ListenersManager.java
  src/main/java/fr/openmc/core/features/economy/EconomyManager.java
  src/main/java/fr/openmc/core/listeners/PlayerDeadListener.java
  src/main/java/fr/openmc/core/listeners/PlayerDeathListener.java
  src/main/java/fr/openmc/core/utils/messages/Prefix.java
Labels: :arrows_counterclockwise: Changement

#380 Ajout d'un reward pending sur les quests
  src/main/java/fr/openmc/core/features/adminshop/AdminShopManager.java
  src/main/java/fr/openmc/core/features/quests/QuestProgressSaveManager.java
  src/main/java/fr/openmc/core/features/quests/menus/QuestsMenu.java
  src/main/java/fr/openmc/core/features/quests/objects/Quest.java
  src/main/java/fr/openmc/core/features/quests/rewards/QuestItemReward.java
  src/main/java/fr/openmc/core/features/quests/rewards/QuestMoneyReward.java
  src/main/java/fr/openmc/core/listeners/JoinMessageListener.java
Labels: :package: Features, :sparkles: Fixes

#389 Add ItemsAdder verification for Mascot
  src/main/java/fr/openmc/core/features/city/CityManager.java
  src/main/java/fr/openmc/core/features/city/mascots/CustomItemsMascotListener.java
  src/main/java/fr/openmc/core/features/city/mascots/MascotsListener.java
Labels: :sparkles: Fixes

#399 Amélioration des protections des claims
  src/main/java/fr/openmc/core/features/city/listeners/ProtectionListener.java
Labels: :sparkles: Fixes, 🆙 Amélioration

#405 Entreprise command permission
  src/main/java/fr/openmc/core/features/corporation/commands/CompanyCommand.java
  src/main/java/fr/openmc/core/features/corporation/commands/ShopCommand.java
Labels: :sparkles: Fixes

#404 Fix Crash de la commande /city list
  src/main/java/fr/openmc/core/features/city/menu/list/CityListDetailsMenu.java
  src/main/java/fr/openmc/core/features/city/menu/list/CityListMenu.java
Labels: :sparkles: Fixes

#395 add CustomFonts
  .gitignore
  src/main/java/fr/openmc/core/features/homes/menu/HomeConfigMenu.java
  src/main/java/fr/openmc/core/utils/customfonts/CustomFonts.java
  src/main/java/fr/openmc/core/utils/customfonts/Fonts.java
Labels: 🆙 Amélioration

#434 Correctif sur les Claims (armor stand et pvp)
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/fr/openmc/core/features/city/listeners/ProtectionListener.java
  src/main/java/fr/openmc/core/features/city/mayor/managers/MayorManager.java
  src/main/java/fr/openmc/core/features/city/menu/mayor/MayorLawMenu.java
Labels: :sparkles: Fixes

#437 Fix l'arrondi du pourcentage des quêtes
  src/main/java/fr/openmc/core/features/quests/menus/QuestsMenu.java
Labels: :sparkles: Fixes

#435 Mise a jour du scoreboard toutes les secondes quand le serveur rédémarre
  src/main/java/fr/openmc/core/commands/utils/Restart.java
  src/main/java/fr/openmc/core/features/scoreboards/ScoreboardManager.java
Labels: 🆙 Amélioration

#402 Change le temp d'absobrissement qd /spawn
  src/main/java/fr/openmc/core/commands/utils/Spawn.java
Labels: 🆙 Amélioration

#438 Fix du bug des packets de leaderboards
  src/main/java/fr/openmc/core/features/leaderboards/LeaderboardManager.java
  src/main/java/fr/openmc/core/features/leaderboards/listeners/LeaderboardListener.java
Labels: :sparkles: Fixes

#431 Fix et changements sur les Maires
  src/main/java/fr/openmc/core/features/city/commands/AdminCityCommands.java
  src/main/java/fr/openmc/core/features/city/commands/AdminMayorCommands.java
  src/main/java/fr/openmc/core/features/city/mayor/listeners/JoinListener.java
  src/main/java/fr/openmc/core/features/city/mayor/listeners/UrneListener.java
  src/main/java/fr/openmc/core/features/city/mayor/managers/MayorManager.java
  src/main/java/fr/openmc/core/features/city/mayor/managers/NPCManager.java
  src/main/java/fr/openmc/core/features/city/mayor/managers/PerkManager.java
  src/main/java/fr/openmc/core/features/city/mayor/perks/basic/AyweniterPerk.java
  src/main/java/fr/openmc/core/features/city/mayor/perks/basic/CityHunterPerk.java
  src/main/java/fr/openmc/core/features/city/mayor/perks/basic/GPSTrackerPerk.java
  src/main/java/fr/openmc/core/features/city/mayor/perks/basic/RagePerk.java
  src/main/java/fr/openmc/core/features/city/mayor/perks/event/MineralRushPerk.java
  src/main/java/fr/openmc/core/features/city/menu/mayor/MayorElectionMenu.java
  src/main/java/fr/openmc/core/features/city/menu/mayor/MayorLawMenu.java
  src/main/java/fr/openmc/core/features/city/menu/mayor/MayorMandateMenu.java
  src/main/java/fr/openmc/core/features/city/menu/mayor/MayorVoteMenu.java
  src/main/java/fr/openmc/core/features/city/menu/mayor/MoreInfoMenu.java
  src/main/java/fr/openmc/core/features/city/menu/mayor/npc/OwnerNpcMenu.java
Labels: :sparkles: Fixes, 🆙 Amélioration

#440 Correctif sur le Build du plugin + Correctif sur /city mayor
  src/main/java/fr/openmc/core/features/city/commands/CityCommands.java
  src/main/java/fr/openmc/core/features/city/menu/mayor/MoreInfoMenu.java
Labels: :sparkles: Fixes

#407 Refonte de la structure des Villes
  src/main/java/fr/openmc/core/features/city/City.java
  src/main/java/fr/openmc/core/features/city/CityManager.java
  src/main/java/fr/openmc/core/features/city/CityMessages.java
  src/main/java/fr/openmc/core/features/city/CityType.java
  src/main/java/fr/openmc/core/features/city/commands/AdminCityCommands.java
  src/main/java/fr/openmc/core/features/city/commands/CityCommands.java
  src/main/java/fr/openmc/core/features/city/listeners/ProtectionListener.java
  src/main/java/fr/openmc/core/features/city/mascots/Mascot.java
  src/main/java/fr/openmc/core/features/city/mascots/MascotUtils.java
  src/main/java/fr/openmc/core/features/city/mascots/MascotsListener.java
  src/main/java/fr/openmc/core/features/city/mascots/MascotsManager.java
  src/main/java/fr/openmc/core/features/city/mayor/perks/basic/MascotFriendlyPerk.java
  src/main/java/fr/openmc/core/features/city/mayor/perks/basic/SymbiosisPerk.java
  src/main/java/fr/openmc/core/features/city/menu/CityChunkMenu.java
  src/main/java/fr/openmc/core/features/city/menu/CityMenu.java
  src/main/java/fr/openmc/core/features/city/menu/CityModifyMenu.java
  src/main/java/fr/openmc/core/features/city/menu/CityTypeMenu.java
  src/main/java/fr/openmc/core/features/city/menu/NoCityMenu.java
  src/main/java/fr/openmc/core/features/city/menu/list/CityListDetailsMenu.java
  src/main/java/fr/openmc/core/features/city/menu/list/CityListMenu.java
  src/main/java/fr/openmc/core/features/city/menu/mascots/MascotMenu.java
  src/main/java/fr/openmc/core/features/city/menu/mascots/MascotsDeadMenu.java
Labels: 🆙 Amélioration

#410 Ajout d'un message de lancement du plugin
  src/main/java/fr/openmc/core/OMCPlugin.java
  src/main/java/fr/openmc/core/features/corporation/shops/Shop.java
Labels: :package: Features

#356 Ajout de l'anti-double-compte et de l'anti-VPN
  src/main/java/fr/openmc/core/OMCPlugin.java
  src/main/java/fr/openmc/core/features/accountdetection/AccountDetectionManager.java
  src/main/java/fr/openmc/core/features/accountdetection/commands/AccountDetectionCommand.java
  src/main/java/fr/openmc/core/utils/DiscordWebhook.java
  src/main/java/fr/openmc/core/utils/messages/Prefix.java
  src/main/resources/data/accountdetection.yml
Labels: :package: Features

#442 Correctif sur les prefix dans le city list menu
  src/main/java/fr/openmc/core/features/city/menu/playerlist/CityPlayerListMenu.java
Labels: :sparkles: Fixes

#448 Modifie le README.md
  README.md
Labels: 🆙 Amélioration

#457 Pouvoir modifier son home par le menu de panneau
  src/main/java/fr/openmc/api/input/signgui/wrapper/MojangWrapper.java
  src/main/java/fr/openmc/core/features/homes/command/RelocateHome.java
  src/main/java/fr/openmc/core/features/homes/command/RenameHome.java
  src/main/java/fr/openmc/core/features/homes/command/SetHome.java
  src/main/java/fr/openmc/core/features/homes/menu/HomeConfigMenu.java
  src/main/java/fr/openmc/core/features/homes/utils/HomeUtil.java
Labels: :arrows_counterclockwise: Changement

#454 [FEAT] Ajoute 4 nouvelles quêtes
  src/main/java/fr/openmc/core/features/quests/QuestsManager.java
  src/main/java/fr/openmc/core/features/quests/quests/BreakLogQuest.java
  src/main/java/fr/openmc/core/features/quests/quests/BreakWheatQuest.java
  src/main/java/fr/openmc/core/features/quests/quests/ChickenThrowerQuest.java
  src/main/java/fr/openmc/core/features/quests/quests/FishingQuest.java
Labels: :package: Features
