Repository ServerOpenMC/PluginV2, pull requests merged in 2025-07, with the labels that each got.

#636 Correctif sur le transfer des Villes
  src/main/java/fr/openmc/core/features/city/CityManager.java
  src/main/java/fr/openmc/core/features/city/commands/CityCommands.java
  src/main/java/fr/openmc/core/features/city/conditions/CityManageConditions.java
Labels: :sparkles: Fixes

#653 resolve conflits
  src/main/java/fr/openmc/core/features/milestones/tutorial/quests/BreakAyweniteQuest.java
  src/main/java/fr/openmc/core/features/milestones/tutorial/quests/HomeCreateQuest.java
  src/main/java/fr/openmc/core/features/milestones/tutorial/quests/HomeUpgradeQuest.java
  src/main/java/fr/openmc/core/features/milestones/tutorial/quests/OpenContestMenuQuest.java
Labels: :sparkles: Fixes, :warning: Urgent

#651 Fix aywenite type
  src/main/java/fr/openmc/core/features/city/actions/CityChestAction.java
  src/main/java/fr/openmc/core/features/city/actions/CityClaimAction.java
  src/main/java/fr/openmc/core/features/city/actions/CityCreateAction.java
  src/main/java/fr/openmc/core/features/city/conditions/CityChestConditions.java
  src/main/java/fr/openmc/core/features/city/conditions/CityCreateConditions.java
  src/main/java/fr/openmc/core/features/city/sub/mascots/MascotsManager.java
  src/main/java/fr/openmc/core/features/city/sub/mascots/menu/MascotMenu.java
  src/main/java/fr/openmc/core/features/city/sub/mascots/menu/MascotsDeadMenu.java
  src/main/java/fr/openmc/core/features/city/sub/mascots/menu/MascotsSkinMenu.java
  src/main/java/fr/openmc/core/features/contest/menu/ContributionMenu.java
  src/main/java/fr/openmc/core/features/contest/menu/TradeMenu.java
  src/main/java/fr/openmc/core/features/homes/HomeUpgradeManager.java
  src/main/java/fr/openmc/core/utils/ItemUtils.java
Labels: :sparkles: Fixes

#663 Correctif de la téléportation lorsque le joueur concerné est dans une ville
  src/main/java/fr/openmc/core/features/city/listeners/protections/TeleportProtection.java
Labels: :lady_beetle: Bug Report

#664 Correctif des dégats pris par la Mascotte du a une autre entité
  src/main/java/fr/openmc/core/features/city/sub/mascots/MascotsManager.java
  src/main/java/fr/openmc/core/features/city/sub/mascots/listeners/MascotsDamageListener.java
  src/main/java/fr/openmc/core/features/city/sub/mascots/listeners/MascotsTargetListener.java
Labels: :sparkles: Fixes

#669 Correctif sur les Hologrammes qui n'apparaissaient pas
  src/main/java/fr/openmc/core/utils/entities/TextDisplay.java
Labels: :sparkles: Fixes

#668 Correctif sur les Tests Unitaires
  src/main/java/fr/openmc/core/features/city/sub/mayor/managers/MayorManager.java
  src/main/java/fr/openmc/core/items/CustomItemRegistry.java
  src/test/java/fr/openmc/core/OMCPluginTest.java
  src/test/java/fr/openmc/core/utils/MotdUtilsTest.java
Labels: :sparkles: Fixes

#665 Changement de la quete CraftKebabQuest en CraftTheMixtureQuest
  src/main/java/fr/openmc/core/features/quests/QuestsManager.java
  src/main/java/fr/openmc/core/features/quests/quests/CraftTheMixtureQuest.java
  src/main/java/fr/openmc/core/items/CustomItemRegistry.java
Labels: :arrows_counterclockwise: Changement

#666 Ajout des Particules au Spawn (lors du Contests et sans le Contest)
  src/main/java/fr/openmc/core/OMCPlugin.java
  src/main/java/fr/openmc/core/features/contest/managers/ContestManager.java
  src/main/java/fr/openmc/core/utils/ColorUtils.java
  src/main/java/fr/openmc/core/utils/ParticleUtils.java
Labels: :package: Features

#670 Passage a la 1.21.8
  README.md
  build.gradle
  src/main/java/fr/openmc/api/input/DialogInput.java
  src/main/java/fr/openmc/api/input/signgui/SignEditor.java
  src/main/java/fr/openmc/api/input/signgui/SignGUI.java
  src/main/java/fr/openmc/api/input/signgui/SignGUIAction.java
  src/main/java/fr/openmc/api/input/signgui/SignGUIBuilder.java
  src/main/java/fr/openmc/api/input/signgui/SignGUIChannelHandler.java
  src/main/java/fr/openmc/api/input/signgui/SignGUIFinishHandler.java
  src/main/java/fr/openmc/api/input/signgui/SignGUIResult.java
  src/main/java/fr/openmc/api/input/signgui/exception/SignGUIException.java
  src/main/java/fr/openmc/api/input/signgui/exception/SignGUIVersionException.java
  src/main/java/fr/openmc/api/input/signgui/wrapper/MojangWrapper.java
  src/main/java/fr/openmc/core/ListenersManager.java
  src/main/java/fr/openmc/core/OMCPlugin.java
  src/main/java/fr/openmc/core/features/city/City.java
  src/main/java/fr/openmc/core/features/city/CityManager.java
  src/main/java/fr/openmc/core/features/city/ProtectionsManager.java
  src/main/java/fr/openmc/core/features/city/actions/CityClaimAction.java
  src/main/java/fr/openmc/core/features/city/actions/CityRankAction.java
  src/main/java/fr/openmc/core/features/city/commands/CityCommands.java
  src/main/java/fr/openmc/core/features/city/menu/CityModifyMenu.java
  src/main/java/fr/openmc/core/features/city/menu/NoCityMenu.java
  src/main/java/fr/openmc/core/features/city/menu/playerlist/CityPlayerListMenu.java
  src/main/java/fr/openmc/core/features/city/menu/ranks/CityRankIconMenu.java
  src/main/java/fr/openmc/core/features/city/models/DBCityClaim.java
  src/main/java/fr/openmc/core/features/city/sub/bank/menu/CityBankDepositMenu.java
  src/main/java/fr/openmc/core/features/city/sub/bank/menu/CityBankWithdrawMenu.java
  src/main/java/fr/openmc/core/features/city/sub/mayor/menu/MayorLawMenu.java
  src/main/java/fr/openmc/core/features/city/sub/mayor/perks/event/IdyllicRain.java
  src/main/java/fr/openmc/core/features/city/sub/mayor/perks/event/MilitaryDissuasion.java
  src/main/java/fr/openmc/core/features/city/sub/war/WarManager.java
  src/main/java/fr/openmc/core/features/contest/menu/TradeMenu.java
  src/main/java/fr/openmc/core/features/corporation/menu/shop/ShopSearchMenu.java
  src/main/java/fr/openmc/core/features/displays/holograms/HologramLoader.java
  src/main/java/fr/openmc/core/features/economy/menu/PersonalBankDepositMenu.java
  src/main/java/fr/openmc/core/features/economy/menu/PersonalBankWithdrawMenu.java
  src/main/java/fr/openmc/core/features/homes/menu/HomeChangeIconMenu.java
  src/main/java/fr/openmc/core/features/homes/menu/HomeConfigMenu.java
  src/main/java/fr/openmc/core/features/homes/utils/HomeUtil.java
  src/main/java/fr/openmc/core/listeners/HappyGhastListener.java
  src/main/java/fr/openmc/core/utils/ChunkPos.java
  src/main/java/fr/openmc/core/utils/InputUtils.java
  src/main/java/fr/openmc/core/utils/ParticleUtils.java
  src/main/java/fr/openmc/core/utils/RandomUtils.java
  src/main/java/fr/openmc/core/utils/dialog/ButtonType.java
  src/main/resources/data/motd.yml
  src/main/resources/plugin.yml
  src/test/resources/plugin.yml
  third_party_licenses/SignGUI_LICENSE
Labels: :video_game: Game Update
