Repository ServerOpenMC/PluginV2, pull requests merged in 2025-06, with the labels that each got.

#372 Ajout de l'événement ContestEvent pour gérer les résultats des contests et les intégrer aux quêtes
  src/main/java/fr/openmc/core/features/city/menu/mayor/MoreInfoMenu.java
  src/main/java/fr/openmc/core/features/contest/ContestEndEvent.java
  src/main/java/fr/openmc/core/features/contest/managers/ContestManager.java
  src/main/java/fr/openmc/core/features/quests/objects/Quest.java
  src/main/java/fr/openmc/core/features/quests/quests/WinContestQuest.java
  src/main/java/fr/openmc/core/listeners/JoinMessageListener.java
  src/main/java/fr/openmc/core/utils/ItemUtils.java
  src/main/resources/data/contest.yml
Labels: :sparkles: Fixes

#479 [FIX] Ajoute la "sauvegarde" de l'état de la bossbar pour un joueur
  src/main/java/fr/openmc/core/features/bossbar/BossbarManager.java
Labels: :arrows_counterclockwise: Changement

#476 Fix du Slot bugé dans le CityChestMenu
  src/main/java/fr/openmc/core/features/city/menu/CityChestMenu.java
Labels: :sparkles: Fixes

#432 Correctif Entreprise et Shop
  src/main/java/fr/openmc/core/features/corporation/commands/CompanyCommand.java
  src/main/java/fr/openmc/core/features/corporation/commands/ShopCommand.java
  src/main/java/fr/openmc/core/features/corporation/company/Company.java
  src/main/java/fr/openmc/core/features/corporation/manager/CompanyManager.java
  src/main/java/fr/openmc/core/features/corporation/manager/PlayerShopManager.java
  src/main/java/fr/openmc/core/features/corporation/menu/company/CompanyBaltopMenu.java
  src/main/java/fr/openmc/core/features/corporation/menu/company/CompanyMenu.java
  src/main/java/fr/openmc/core/features/corporation/menu/company/CompanySearchMenu.java
  src/main/java/fr/openmc/core/features/corporation/menu/shop/ShopCatalogueMenu.java
  src/main/java/fr/openmc/core/features/corporation/menu/shop/ShopMenu.java
  src/main/java/fr/openmc/core/features/corporation/menu/shop/ShopSalesMenu.java
  src/main/java/fr/openmc/core/features/corporation/menu/shop/ShopStocksMenu.java
  src/main/java/fr/openmc/core/features/corporation/shops/Shop.java
  src/main/java/fr/openmc/core/features/corporation/shops/ShopItem.java
  src/main/java/fr/openmc/core/utils/database/DatabaseManager.java
Labels: :sparkles: Fixes

#492 Ajout des messages privées
  src/main/java/fr/openmc/core/CommandsManager.java
  src/main/java/fr/openmc/core/OMCPlugin.java
  src/main/java/fr/openmc/core/features/privatemessage/PrivateMessageManager.java
  src/main/java/fr/openmc/core/features/privatemessage/SocialSpyManager.java
  src/main/java/fr/openmc/core/features/privatemessage/command/PrivateMessageCommand.java
  src/main/java/fr/openmc/core/features/privatemessage/command/SocialSpyCommand.java
Labels: :package: Features

#496 Correctif sur les NPC qui vole lorsqu'on pose l'urne
  src/main/java/fr/openmc/core/features/city/mayor/listeners/UrneListener.java
Labels: :sparkles: Fixes

#498 Correctif sur l'emplacement des items dans le baltop des entreprises
  src/main/java/fr/openmc/core/features/corporation/menu/company/CompanyBaltopMenu.java
Labels: :sparkles: Fixes

#499 Ajout d'un indicateur pour le cooldown de creation de ville
  src/main/java/fr/openmc/core/features/city/menu/CityModifyMenu.java
  src/main/java/fr/openmc/core/features/city/menu/NoCityMenu.java
Labels: 🆙 Amélioration

#500 Tentative de correctif de l'ordre dans les Contests
  .gitignore
  src/main/java/fr/openmc/core/features/contest/managers/ContestPlayerManager.java
  src/main/java/fr/openmc/core/features/contest/models/ContestPlayer.java
Labels: :sparkles: Fixes

#502 Correctif sur la duplication du cube
  src/main/java/fr/openmc/core/ListenersManager.java
  src/main/java/fr/openmc/core/OMCPlugin.java
  src/main/java/fr/openmc/core/listeners/CubeListener.java
Labels: :sparkles: Fixes

#503 Correctif sur celui qui regarde le coffre + QoL
  src/main/java/fr/openmc/core/features/city/commands/CityChestCommand.java
  src/main/java/fr/openmc/core/features/city/conditions/CityChestConditions.java
  src/main/java/fr/openmc/core/features/city/menu/CityChestMenu.java
  src/main/java/fr/openmc/core/features/city/menu/CityMenu.java
Labels: :sparkles: Fixes, 🆙 Amélioration

#510 Hotfix
  src/main/java/fr/openmc/core/features/city/mascots/MascotUtils.java
  src/main/java/fr/openmc/core/features/city/mascots/MascotsListener.java
  src/main/java/fr/openmc/core/features/city/models/DBCity.java
Labels: :sparkles: Fixes

#535 Correctif sur l'activation des Réformes
  src/main/java/fr/openmc/core/features/city/sub/mayor/managers/MayorManager.java
Labels: :sparkles: Fixes

#512 Ajout du /settings
  src/main/java/fr/openmc/core/CommandsManager.java
  src/main/java/fr/openmc/core/ListenersManager.java
  src/main/java/fr/openmc/core/OMCPlugin.java
  src/main/java/fr/openmc/core/commands/utils/Rtp.java
  src/main/java/fr/openmc/core/commands/utils/Spawn.java
  src/main/java/fr/openmc/core/features/city/conditions/CityInviteConditions.java
  src/main/java/fr/openmc/core/features/friend/FriendCommand.java
  src/main/java/fr/openmc/core/features/friend/FriendManager.java
  src/main/java/fr/openmc/core/features/homes/HomesManager.java
  src/main/java/fr/openmc/core/features/homes/command/TpHome.java
  src/main/java/fr/openmc/core/features/mailboxes/MailboxManager.java
  src/main/java/fr/openmc/core/features/privatemessage/PrivateMessageManager.java
  src/main/java/fr/openmc/core/features/settings/PlayerSettings.java
  src/main/java/fr/openmc/core/features/settings/PlayerSettingsManager.java
  src/main/java/fr/openmc/core/features/settings/SettingType.java
  src/main/java/fr/openmc/core/features/settings/ValueType.java
  src/main/java/fr/openmc/core/features/settings/command/SettingsCommand.java
  src/main/java/fr/openmc/core/features/settings/menu/PlayerSettingsMenu.java
  src/main/java/fr/openmc/core/features/settings/models/PlayerSettingEntity.java
  src/main/java/fr/openmc/core/features/settings/policy/CityPolicy.java
  src/main/java/fr/openmc/core/features/settings/policy/FriendPolicy.java
  src/main/java/fr/openmc/core/features/settings/policy/GlobalPolicy.java
  src/main/java/fr/openmc/core/features/settings/policy/Policy.java
  src/main/java/fr/openmc/core/features/tpa/commands/TPAcceptCommand.java
  src/main/java/fr/openmc/core/utils/PlayerUtils.java
  src/main/java/fr/openmc/core/utils/database/DatabaseManager.java
  src/main/java/fr/openmc/core/utils/messages/MessagesManager.java
  src/main/java/fr/openmc/core/utils/messages/Prefix.java
Labels: :package: Features

#549 Correctif du /tpaccept
  src/main/java/fr/openmc/core/features/tpa/commands/TPAcceptCommand.java
Labels: :sparkles: Fixes

#554 Correctif des Claims dans les Villes
  src/main/java/fr/openmc/core/features/city/CityManager.java
  src/main/java/fr/openmc/core/features/city/ProtectionsManager.java
  src/main/java/fr/openmc/core/features/city/listeners/protections/InteractProtection.java
  src/main/java/fr/openmc/core/features/city/listeners/protections/VehicleProtection.java
  src/main/java/fr/openmc/core/features/city/sub/mascots/models/Mascot.java
Labels: :sparkles: Fixes

#565 Remove bordered material
  src/main/java/fr/openmc/core/features/corporation/menu/company/CompanyBankTransactionsMenu.java
  src/main/java/fr/openmc/core/features/corporation/menu/company/CompanyMenu.java
  src/main/java/fr/openmc/core/features/corporation/menu/company/CompanySearchMenu.java
  src/main/java/fr/openmc/core/features/corporation/menu/company/ShopManageMenu.java
  src/main/java/fr/openmc/core/features/corporation/menu/shop/ShopCatalogueMenu.java
  src/main/java/fr/openmc/core/features/corporation/menu/shop/ShopMenu.java
  src/main/java/fr/openmc/core/features/corporation/menu/shop/ShopSalesMenu.java
  src/main/java/fr/openmc/core/features/corporation/menu/shop/ShopSearchMenu.java
  src/main/java/fr/openmc/core/features/corporation/menu/shop/ShopStocksMenu.java
Labels: :sparkles: Fixes

#588 Fix les pseudos modifiant les messages de VPN
  src/main/java/fr/openmc/core/features/accountdetection/AccountDetectionManager.java
Labels: :sparkles: Fixes

#590 Fix la commande /rtp ne fonctionnant pas
  src/main/java/fr/openmc/core/commands/utils/Rtp.java
Labels: :sparkles: Fixes

#603 Fix l'avancée de quête quand on craft plusieurs kebabs
  src/main/java/fr/openmc/core/features/quests/quests/CraftKebabQuest.java
  src/main/java/fr/openmc/core/utils/ItemUtils.java
Labels: :sparkles: Fixes

#504 Ajour d'un Menu qui liste tous les membres d'une ville pour le /city list
  src/main/java/fr/openmc/core/features/city/menu/bank/CityBankDepositMenu.java
  src/main/java/fr/openmc/core/features/city/menu/bank/CityBankMenu.java
  src/main/java/fr/openmc/core/features/city/menu/bank/CityBankWithdrawMenu.java
  src/main/java/fr/openmc/core/features/city/menu/list/CityListDetailsMenu.java
  src/main/java/fr/openmc/core/features/city/menu/list/CityListMenu.java
  src/main/java/fr/openmc/core/features/city/menu/list/CityPlayerListMenu.java
  src/main/java/fr/openmc/core/features/city/menu/mascots/MascotMenu.java
  src/main/java/fr/openmc/core/features/city/menu/mascots/MascotsDeadMenu.java
  src/main/java/fr/openmc/core/features/city/menu/mayor/MayorElectionMenu.java
  src/main/java/fr/openmc/core/features/city/menu/mayor/MayorLawMenu.java
  src/main/java/fr/openmc/core/features/city/menu/mayor/MayorMandateMenu.java
  src/main/java/fr/openmc/core/features/city/menu/mayor/MoreInfoMenu.java
  src/main/java/fr/openmc/core/features/city/menu/mayor/create/MayorColorMenu.java
  src/main/java/fr/openmc/core/features/city/menu/mayor/create/MayorCreateMenu.java
  src/main/java/fr/openmc/core/features/city/menu/mayor/create/MayorModifyMenu.java
  src/main/java/fr/openmc/core/features/city/menu/mayor/npc/OwnerNpcMenu.java
  src/main/java/fr/openmc/core/utils/ColorUtils.java
Labels: 🆙 Amélioration

#607 Correctif de l'effet de la réforme Mineur Fou
  src/main/java/fr/openmc/core/features/city/sub/mayor/perks/basic/MinerPerk.java
Labels: :sparkles: Fixes

#616 Correctif sur le message pour prévenir qu'on a des lettres
  src/main/java/fr/openmc/core/features/mailboxes/MailboxManager.java
Labels: :sparkles: Fixes

#615 Correctif sur la téléportation lors du début d'une guerre
  src/main/java/fr/openmc/core/features/city/listeners/protections/BlockProtection.java
  src/main/java/fr/openmc/core/features/city/sub/mayor/listeners/UrneListener.java
  src/main/java/fr/openmc/core/features/city/sub/war/War.java
  src/main/java/fr/openmc/core/features/city/sub/war/WarManager.java
  src/main/java/fr/openmc/core/features/city/sub/war/listeners/TntPlaceListener.java
  src/main/java/fr/openmc/core/utils/LocationUtils.java
  src/main/java/fr/openmc/core/utils/MaterialUtils.java
Labels: :sparkles: Fixes

#611 Correctif sur les claims des villes (Ender pearl lost/Unclaiming issue/Arrow lost/war player hit)
  src/main/java/fr/openmc/core/features/city/CityManager.java
  src/main/java/fr/openmc/core/features/city/ProtectionsManager.java
  src/main/java/fr/openmc/core/features/city/listeners/protections/BowProtection.java
  src/main/java/fr/openmc/core/features/city/listeners/protections/DamageProtection.java
  src/main/java/fr/openmc/core/features/city/listeners/protections/TeleportProtection.java
Labels: :sparkles: Fixes

#614 Ajout d'un Menu de Confirmation pour reset ces settings
  src/main/java/fr/openmc/core/features/settings/menu/PlayerSettingsMenu.java
Labels: 🆙 Amélioration

#622 Changement des trades des contests fait par Mcross et Rylo
  src/main/resources/data/contest.yml
Labels: :arrows_counterclockwise: Changement

#595 Correctif du /city mayor qui renvoyait un menu incorrect
  src/main/java/fr/openmc/core/features/city/menu/CityMenu.java
  src/main/java/fr/openmc/core/features/city/sub/mayor/actions/MayorCommandAction.java
  src/main/java/fr/openmc/core/features/city/sub/mayor/commands/MayorCommands.java
Labels: :sparkles: Fixes

#625 Amelioration sur l'affichage des Contests, DIRT_BLOCK => Bloc de Terre
  src/main/java/fr/openmc/core/features/contest/menu/TradeMenu.java
  src/main/java/fr/openmc/core/utils/ItemUtils.java
Labels: 🆙 Amélioration

#618 Tentative de correctif sur les Upgrades des Homes
  src/main/java/fr/openmc/core/features/homes/HomesManager.java
Labels: :sparkles: Fixes

#396 Ajout du menu principal
  src/main/java/fr/openmc/api/packetmenulib/PacketListener.java
  src/main/java/fr/openmc/api/packetmenulib/PacketMenuLib.java
  src/main/java/fr/openmc/api/packetmenulib/events/InventoryClickEvent.java
  src/main/java/fr/openmc/api/packetmenulib/events/InventoryCloseEvent.java
  src/main/java/fr/openmc/api/packetmenulib/menu/ClickType.java
  src/main/java/fr/openmc/api/packetmenulib/menu/InventoryType.java
  src/main/java/fr/openmc/api/packetmenulib/menu/Menu.java
  src/main/java/fr/openmc/api/packetmenulib/utils/PacketUtils.java
  src/main/java/fr/openmc/core/CommandsManager.java
  src/main/java/fr/openmc/core/OMCPlugin.java
  src/main/java/fr/openmc/core/features/analytics/Stats.java
  src/main/java/fr/openmc/core/features/city/commands/CityCommands.java
  src/main/java/fr/openmc/core/features/contest/commands/ContestCommand.java
  src/main/java/fr/openmc/core/features/corporation/commands/CompanyCommand.java
  src/main/java/fr/openmc/core/features/corporation/commands/ShopCommand.java
  src/main/java/fr/openmc/core/features/economy/commands/BankCommands.java
  src/main/java/fr/openmc/core/features/homes/command/TpHome.java
  src/main/java/fr/openmc/core/features/mailboxes/MailboxCommand.java
  src/main/java/fr/openmc/core/features/mainmenu/MainMenu.java
  src/main/java/fr/openmc/core/features/mainmenu/commands/MainMenuCommand.java
  src/main/java/fr/openmc/core/features/mainmenu/listeners/PacketListener.java
  src/main/java/fr/openmc/core/features/mainmenu/menus/Page1.java
  src/main/java/fr/openmc/core/features/mainmenu/menus/Page2.java
  src/main/java/fr/openmc/core/features/quests/command/QuestCommand.java
  src/main/java/fr/openmc/core/features/settings/command/SettingsCommand.java
Labels: :package: Features
