Repository ServerOpenMC/PluginV2, pull requests merged in 2025-09, with the labels that each got.

#728 Ajout de l'animation de spawn
  src/main/java/fr/openmc/core/OMCPlugin.java
  src/main/java/fr/openmc/core/features/animations/Animation.java
  src/main/java/fr/openmc/core/features/animations/AnimationsManager.java
  src/main/java/fr/openmc/core/features/animations/PlayerAnimationInfo.java
  src/main/java/fr/openmc/core/features/animations/listeners/EmoteListener.java
  src/main/java/fr/openmc/core/features/animations/listeners/PlayerFinishJoiningListener.java
  src/main/resources/data/animations/join_rift.animation.json
Labels: :package: Feature

#729 Ajout de la Casquette Aywen
  src/main/java/fr/openmc/core/ListenersManager.java
  src/main/java/fr/openmc/core/items/CustomItemRegistry.java
  src/main/java/fr/openmc/core/listeners/AywenCapListener.java
Labels: :package: Feature

#730 Changement ItemUtils.
  src/main/java/fr/openmc/core/utils/ItemUtils.java
Labels: :arrows_counterclockwise: Changement

#731 Aurtograf
  .github/ISSUE_TEMPLATE/demande-de-changement-.md
  .github/ISSUE_TEMPLATE/demande-de-feature.md
  build.gradle
  src/main/java/fr/openmc/api/chronometer/Chronometer.java
  src/main/java/fr/openmc/api/cooldown/DynamicCooldownManager.java
  src/main/java/fr/openmc/api/input/location/ItemInteraction.java
  src/main/java/fr/openmc/api/menulib/default_menu/ConfirmMenu.java
  src/main/java/fr/openmc/api/menulib/utils/MenuUtils.java
  src/main/java/fr/openmc/api/packetmenulib/PacketListener.java
  src/main/java/fr/openmc/core/disabled/corporation/company/Company.java
  src/main/java/fr/openmc/core/disabled/corporation/listener/ShopListener.java
  src/main/java/fr/openmc/core/disabled/corporation/manager/CompanyManager.java
  src/main/java/fr/openmc/core/disabled/corporation/manager/PlayerShopManager.java
  src/main/java/fr/openmc/core/disabled/corporation/models/ShopSupplier.java
  src/main/java/fr/openmc/core/disabled/corporation/shops/Shop.java
  src/main/java/fr/openmc/core/features/city/City.java
  src/main/java/fr/openmc/core/features/city/menu/CityMenu.java
  src/main/java/fr/openmc/core/features/city/sub/bank/CityBankManager.java
  src/main/java/fr/openmc/core/features/city/sub/mascots/listeners/MascotsDeathListener.java
  src/main/java/fr/openmc/core/features/city/sub/mayor/listeners/PhaseListener.java
  src/main/java/fr/openmc/core/features/city/sub/mayor/managers/MayorManager.java
  src/main/java/fr/openmc/core/features/city/sub/mayor/menu/MayorLawMenu.java
  src/main/java/fr/openmc/core/features/city/sub/mayor/menu/create/MenuType.java
  src/main/java/fr/openmc/core/features/city/sub/mayor/perks/basic/RagePerk.java
  src/main/java/fr/openmc/core/features/city/sub/mayor/perks/event/AgriculturalEssorPerk.java
  src/main/java/fr/openmc/core/features/city/sub/mayor/perks/readme.md
  src/main/java/fr/openmc/core/features/city/sub/milestone/requirements/ItemDepositRequirement.java
  src/main/java/fr/openmc/core/features/city/sub/milestone/rewards/InterestRewards.java
  src/main/java/fr/openmc/core/features/city/sub/statistics/CityStatisticsManager.java
  src/main/java/fr/openmc/core/features/city/sub/statistics/listeners/MemberJoinListener.java
  src/main/java/fr/openmc/core/features/city/sub/war/War.java
  src/main/java/fr/openmc/core/features/city/sub/war/WarManager.java
  src/main/java/fr/openmc/core/features/city/sub/war/actions/WarActions.java
  src/main/java/fr/openmc/core/features/contest/commands/ContestCommand.java
  src/main/java/fr/openmc/core/features/contest/managers/ContestManager.java
  src/main/java/fr/openmc/core/features/contest/managers/ContestPlayerManager.java
  src/main/java/fr/openmc/core/features/contest/managers/TradeYMLManager.java
  src/main/java/fr/openmc/core/features/economy/BankManager.java
  src/main/java/fr/openmc/core/features/homes/icons/OldHomeIcon.java
  src/main/java/fr/openmc/core/features/milestones/MilestonesManager.java
  src/main/java/fr/openmc/core/features/milestones/tutorial/TutorialStep.java
  src/main/java/fr/openmc/core/features/quests/objects/Quest.java
  src/main/java/fr/openmc/core/features/quests/readme.md
  src/main/java/fr/openmc/core/listeners/SleepListener.java
  src/main/java/fr/openmc/core/utils/ColorUtils.java
  src/main/java/fr/openmc/core/utils/DateUtils.java
  src/main/java/fr/openmc/core/utils/ItemUtils.java
  src/main/java/fr/openmc/core/utils/MotdUtils.java
  src/main/java/fr/openmc/core/utils/serializer/LocationSerializer.java
  src/main/java/fr/openmc/core/utils/translation/TranslationManager.java
  src/main/java/fr/openmc/core/utils/world/WorldUtils.java
  src/main/resources/data/contest.yml
Labels: :arrows_counterclockwise: Changement

#742 Changement du message d'interdiction de claim
  src/main/java/fr/openmc/core/features/city/conditions/CityClaimCondition.java
Labels: :arrows_counterclockwise: Changement

#741 Correctif des boutons Annuler dans les Menus d'Input
  src/main/java/fr/openmc/api/input/DialogInput.java
  src/main/java/fr/openmc/core/disabled/corporation/menu/shop/ShopSearchMenu.java
  src/main/java/fr/openmc/core/features/city/actions/CityCreateAction.java
  src/main/java/fr/openmc/core/features/city/commands/CityCommands.java
  src/main/java/fr/openmc/core/features/city/menu/CityModifyMenu.java
  src/main/java/fr/openmc/core/features/city/menu/NoCityMenu.java
  src/main/java/fr/openmc/core/features/city/menu/playerlist/CityPlayerListMenu.java
  src/main/java/fr/openmc/core/features/city/sub/bank/menu/CityBankDepositMenu.java
  src/main/java/fr/openmc/core/features/city/sub/bank/menu/CityBankWithdrawMenu.java
  src/main/java/fr/openmc/core/features/city/sub/rank/CityRankAction.java
  src/main/java/fr/openmc/core/features/city/sub/rank/menus/CityRankIconMenu.java
  src/main/java/fr/openmc/core/features/economy/menu/PersonalBankDepositMenu.java
  src/main/java/fr/openmc/core/features/economy/menu/PersonalBankWithdrawMenu.java
  src/main/java/fr/openmc/core/features/homes/menu/HomeChangeIconMenu.java
  src/main/java/fr/openmc/core/features/homes/menu/HomeConfigMenu.java
Labels: :sparkles: Fixes

#740 Correctif des conditions des claims
  src/main/java/fr/openmc/core/features/city/conditions/CityClaimCondition.java
Labels: :sparkles: Fixes

#744 Ajout d'un progression dans la boss bar pour la quete BreakAywenite
  src/main/java/fr/openmc/core/features/milestones/tutorial/quests/BreakAyweniteQuest.java
Labels: :arrows_counterclockwise: Changement

#752 Correction du déposit de la banque
  src/main/java/fr/openmc/core/features/city/sub/bank/menu/CityBankDepositMenu.java
Labels: :sparkles: Fixes

#751 Correction de la rotation du corps pendant l'animation de join
  src/main/java/fr/openmc/core/features/animations/listeners/EmoteListener.java
  src/main/java/fr/openmc/core/features/animations/listeners/PlayerFinishJoiningListener.java
Labels: :sparkles: Fixes

#761 Correction du MascotSoundListener
  src/main/java/fr/openmc/core/features/city/sub/mascots/listeners/MascotsSoundListener.java
Labels: :sparkles: Fixes

#759 Correctif des Notations
  src/main/java/fr/openmc/core/features/city/sub/notation/NotationManager.java
Labels: :sparkles: Fixes

#768 Correction sur l'affichage des cooldowns du Milestone des Villes
  src/main/java/fr/openmc/core/features/city/menu/CityMenu.java
  src/main/java/fr/openmc/core/features/city/sub/milestone/menu/CityMilestoneMenu.java
Labels: :sparkles: Fixes

#767 Correction du parametre : mute des Mascottes
  src/main/java/fr/openmc/core/features/city/sub/mascots/listeners/MascotsSoundListener.java
Labels: :sparkles: Fixes

#787 Changement sur la hauteur des particules du /city claim view
  src/main/java/fr/openmc/core/features/city/view/CityViewManager.java
Labels: :arrows_counterclockwise: Changement

#792 Correction de la corruption du fichier yaml des Contests
  src/main/java/fr/openmc/core/features/contest/managers/TradeYMLManager.java
  src/main/java/fr/openmc/core/utils/YmlUtils.java
Labels: :sparkles: Fixes

#794 Ajout de la peluche aywen dans le tuto
  src/main/java/fr/openmc/core/OMCPlugin.java
  src/main/java/fr/openmc/core/features/milestones/tutorial/quests/CityCreateQuest.java
  src/main/java/fr/openmc/core/features/milestones/tutorial/quests/HomeCreateQuest.java
  src/main/java/fr/openmc/core/features/milestones/tutorial/quests/OpenContestMenuQuest.java
  src/main/java/fr/openmc/core/items/CustomItemRegistry.java
  src/main/resources/config.yml
Labels: :arrows_counterclockwise: Changement

#797 Correctif des Sauvegardes des Homes
  src/main/java/fr/openmc/core/features/homes/command/SetHome.java
  src/main/java/fr/openmc/core/features/homes/models/Home.java
Labels: :sparkles: Fixes, :bomb: Change DB

#815 Correctifs sur les Notations (/city notation si aucune ville, sauvegarde)
  src/main/java/fr/openmc/core/features/city/sub/notation/NotationManager.java
  src/main/java/fr/openmc/core/features/city/sub/notation/commands/NotationCommands.java
  src/main/java/fr/openmc/core/features/city/sub/notation/menu/NotationDialog.java
  src/main/java/fr/openmc/core/features/city/sub/notation/models/CityNotation.java
Labels: :sparkles: Fixes

#820 Correctif du ErrorHandler (stacktrace, crash infini)
  src/main/java/fr/openmc/core/OMCPlugin.java
  src/main/java/fr/openmc/core/utils/errors/ErrorReporter.java
Labels: :sparkles: Fixes, 🆙 Amélioration

#822 Changement sur le Cube (sound, correction bulle)
  src/main/java/fr/openmc/core/features/cube/Cube.java
  src/main/java/fr/openmc/core/features/cube/listeners/CubeListener.java
  src/main/java/fr/openmc/core/features/cube/multiblocks/MultiBlockManager.java
Labels: :sparkles: Fixes, 🆙 Amélioration

#833 Fix du TPA quand un joueur quit
  src/main/java/fr/openmc/core/OMCPlugin.java
  src/main/java/fr/openmc/core/features/tpa/TPAManager.java
  src/main/java/fr/openmc/core/features/tpa/TPAQueue.java
  src/main/java/fr/openmc/core/features/tpa/commands/TPACancelCommand.java
  src/main/java/fr/openmc/core/features/tpa/commands/TPACommand.java
  src/main/java/fr/openmc/core/features/tpa/commands/TPADenyCommand.java
  src/main/java/fr/openmc/core/features/tpa/commands/TPAcceptCommand.java
  src/main/java/fr/openmc/core/listeners/JoinMessageListener.java
Labels: :sparkles: Fixes, 🆙 Amélioration

#842 Correctif des Contests
  src/main/java/fr/openmc/core/features/contest/managers/ContestManager.java
  src/main/java/fr/openmc/core/features/mailboxes/MailboxManager.java
  src/main/java/fr/openmc/core/utils/errors/ErrorReporter.java
Labels: :sparkles: Fixes

#848 Correction sur l'ordre des Notations
  src/main/java/fr/openmc/core/features/city/sub/notation/NotationManager.java
Labels: :sparkles: Fixes
