Repository ServerOpenMC/PluginV2, pull requests merged in 2025-04, with the labels that each got.

#127 [ Mascotte ] Bug Fix + Modification
  src/main/java/fr/openmc/core/features/city/CityMessages.java
  src/main/java/fr/openmc/core/features/city/commands/AdminCityCommands.java
  src/main/java/fr/openmc/core/features/city/commands/CityCommands.java
  src/main/java/fr/openmc/core/features/city/mascots/MascotsListener.java
  src/main/java/fr/openmc/core/features/city/mascots/MascotsManager.java
  src/main/java/fr/openmc/core/features/city/menu/CityTypeMenu.java
Labels: :sparkles: Fixes

#138 [ FIX ] Mascotte Glowing effect
  src/main/java/fr/openmc/core/features/city/commands/AdminCityCommands.java
  src/main/java/fr/openmc/core/features/city/mascots/MascotsListener.java
  src/main/java/fr/openmc/core/features/city/mascots/MascotsManager.java
Labels: :sparkles: Fixes

#161 Ajout du /freeze
  src/main/java/fr/openmc/core/OMCPlugin.java
  src/main/java/fr/openmc/core/commands/CommandsManager.java
  src/main/java/fr/openmc/core/features/contest/commands/ContestCommand.java
  src/main/java/fr/openmc/core/features/contest/managers/ContestManager.java
  src/main/java/fr/openmc/core/utils/freeze/FreezeCommand.java
  src/main/java/fr/openmc/core/utils/freeze/FreezeListener.java
  src/main/java/fr/openmc/core/utils/freeze/FreezeManager.java
  src/main/java/fr/openmc/core/utils/menu/MenuUtils.java
  src/main/java/fr/openmc/core/utils/messages/MessagesManager.java
  src/main/java/fr/openmc/core/utils/messages/Prefix.java
  src/main/java/fr/openmc/core/utils/translation/TranslationManager.java
Labels: :package: Features

#165 Optimisation du Code + Clean
  src/main/java/fr/openmc/core/OMCPlugin.java
  src/main/java/fr/openmc/core/commands/debug/CooldownCommand.java
  src/main/java/fr/openmc/core/features/ScoreboardManager.java
  src/main/java/fr/openmc/core/features/city/City.java
  src/main/java/fr/openmc/core/features/city/CityManager.java
  src/main/java/fr/openmc/core/features/city/CityMessages.java
  src/main/java/fr/openmc/core/features/city/commands/CityCommands.java
  src/main/java/fr/openmc/core/features/city/conditions/CityBankConditions.java
  src/main/java/fr/openmc/core/features/city/conditions/CityClaimCondition.java
  src/main/java/fr/openmc/core/features/city/conditions/CityCreateConditions.java
  src/main/java/fr/openmc/core/features/city/conditions/CityInviteConditions.java
  src/main/java/fr/openmc/core/features/city/conditions/CityTypeConditions.java
  src/main/java/fr/openmc/core/features/city/events/CityPermissionChangeEvent.java
  src/main/java/fr/openmc/core/features/city/events/MemberJoinEvent.java
  src/main/java/fr/openmc/core/features/city/listeners/ChestMenuListener.java
  src/main/java/fr/openmc/core/features/city/listeners/ProtectionListener.java
  src/main/java/fr/openmc/core/features/city/mascots/MascotsListener.java
  src/main/java/fr/openmc/core/features/city/mascots/MascotsManager.java
  src/main/java/fr/openmc/core/features/city/menu/ChestMenu.java
  src/main/java/fr/openmc/core/features/city/menu/CityChunkMenu.java
  src/main/java/fr/openmc/core/features/city/menu/CityModifyMenu.java
  src/main/java/fr/openmc/core/features/city/menu/CityTypeMenu.java
  src/main/java/fr/openmc/core/features/city/menu/NoCityMenu.java
  src/main/java/fr/openmc/core/features/city/menu/mascots/MascotMenu.java
  src/main/java/fr/openmc/core/features/contest/ContestPlayer.java
  src/main/java/fr/openmc/core/features/contest/managers/ContestManager.java
  src/main/java/fr/openmc/core/features/contest/managers/ContestPlayerManager.java
  src/main/java/fr/openmc/core/features/economy/EconomyData.java
  src/main/java/fr/openmc/core/features/economy/EconomyManager.java
  src/main/java/fr/openmc/core/features/economy/TransactionsManager.java
  src/main/java/fr/openmc/core/features/friend/FriendSQLManager.java
  src/main/java/fr/openmc/core/features/homes/HomesManager.java
  src/main/java/fr/openmc/core/features/homes/command/TpHome.java
  src/main/java/fr/openmc/core/features/homes/utils/HomeUtil.java
  src/main/java/fr/openmc/core/features/mailboxes/MailboxListener.java
  src/main/java/fr/openmc/core/features/mailboxes/MailboxManager.java
  src/main/java/fr/openmc/core/features/mailboxes/menu/letter/SendingLetter.java
  src/main/java/fr/openmc/core/utils/BlockVector2.java
  src/main/java/fr/openmc/core/utils/WorldGuardApi.java
  src/main/java/fr/openmc/core/utils/customitems/Aywenite.java
  src/main/java/fr/openmc/core/utils/customitems/ContestShell.java
  src/main/java/fr/openmc/core/utils/customitems/CustomItemRegistry.java
  src/main/java/fr/openmc/core/utils/menu/ConfirmMenu.java
Labels: 🆙 Amélioration, ⚡Optimisation

#155 Fix Affichage Free Claim Menu
  src/main/java/fr/openmc/core/features/city/menu/CityChunkMenu.java
Labels: :sparkles: Fixes

#170 Update test units
  .github/workflows/main.yml
  .github/workflows/tests.yml
  build.gradle
  gradlew
  src/test/java/fr/openmc/core/TestPlugin.java
  src/test/java/fr/openmc/core/utils/DateUtilsTest.java
  src/test/java/fr/openmc/core/utils/DateUtilsTests.java
  src/test/java/fr/openmc/core/utils/InputUtilsTest.java
  src/test/java/fr/openmc/core/utils/ItemsUtilTest.java
  src/test/java/fr/openmc/core/utils/MotdUtilsTest.java
Labels: 🆙 Amélioration

#169 Amélioration et Fixe des Protections pour les villes
  src/main/java/fr/openmc/core/features/city/listeners/ProtectionListener.java
Labels: :sparkles: Fixes, 🆙 Amélioration

#181 Fix Bug des Claims
  src/main/java/fr/openmc/core/features/city/commands/CityCommands.java
  src/main/java/fr/openmc/core/features/city/mascots/MascotsManager.java
Labels: :sparkles: Fixes

#185 Ajout des intérets
  src/main/java/fr/openmc/core/features/city/City.java
  src/main/java/fr/openmc/core/features/city/CityManager.java
  src/main/java/fr/openmc/core/features/city/menu/bank/CityBankMenu.java
  src/main/java/fr/openmc/core/features/economy/BankManager.java
  src/main/java/fr/openmc/core/features/economy/EconomyManager.java
  src/main/java/fr/openmc/core/features/economy/commands/BankCommands.java
  src/main/java/fr/openmc/core/features/economy/menu/PersonalBankDepositMenu.java
  src/main/java/fr/openmc/core/features/economy/menu/PersonalBankMenu.java
  src/main/java/fr/openmc/core/features/economy/menu/PersonalBankWithdrawMenu.java
  src/main/java/fr/openmc/core/utils/messages/Prefix.java
Labels: :package: Features

#158 Ajout du système de quest
  src/main/java/fr/openmc/core/OMCPlugin.java
  src/main/java/fr/openmc/core/commands/CommandsManager.java
  src/main/java/fr/openmc/core/features/city/events/CityCreationEvent.java
  src/main/java/fr/openmc/core/features/contest/managers/ContestManager.java
  src/main/java/fr/openmc/core/features/economy/EconomyManager.java
  src/main/java/fr/openmc/core/features/quests/QuestProgressSaveManager.java
  src/main/java/fr/openmc/core/features/quests/QuestsManager.java
  src/main/java/fr/openmc/core/features/quests/command/QuestCommand.java
  src/main/java/fr/openmc/core/features/quests/menus/QuestsMenu.java
  src/main/java/fr/openmc/core/features/quests/objects/Quest.java
  src/main/java/fr/openmc/core/features/quests/objects/QuestBuilder.java
  src/main/java/fr/openmc/core/features/quests/objects/QuestStep.java
  src/main/java/fr/openmc/core/features/quests/objects/QuestTier.java
  src/main/java/fr/openmc/core/features/quests/quests/BreakDiamondQuest.java
  src/main/java/fr/openmc/core/features/quests/quests/BreakStoneQuest.java
  src/main/java/fr/openmc/core/features/quests/quests/CityCreateQuest.java
  src/main/java/fr/openmc/core/features/quests/quests/ConsumeKebabQuest.java
  src/main/java/fr/openmc/core/features/quests/quests/CraftCakeQuest.java
  src/main/java/fr/openmc/core/features/quests/quests/CraftDiamondArmorQuest.java
  src/main/java/fr/openmc/core/features/quests/quests/CraftKebabQuest.java
  src/main/java/fr/openmc/core/features/quests/quests/EnchantFirstItemQuest.java
  src/main/java/fr/openmc/core/features/quests/quests/KillPlayersQuest.java
  src/main/java/fr/openmc/core/features/quests/quests/KillSuperCreeperQuest.java
  src/main/java/fr/openmc/core/features/quests/quests/KillZombieQuest.java
  src/main/java/fr/openmc/core/features/quests/quests/MineAyweniteQuest.java
  src/main/java/fr/openmc/core/features/quests/quests/SaveTheEarthQuest.java
  src/main/java/fr/openmc/core/features/quests/quests/SmeltIronQuest.java
  src/main/java/fr/openmc/core/features/quests/quests/WalkQuests.java
  src/main/java/fr/openmc/core/features/quests/quests/WinContestQuest.java
  src/main/java/fr/openmc/core/features/quests/readme.md
  src/main/java/fr/openmc/core/features/quests/rewards/QuestItemReward.java
  src/main/java/fr/openmc/core/features/quests/rewards/QuestMoneyReward.java
  src/main/java/fr/openmc/core/features/quests/rewards/QuestReward.java
  src/main/java/fr/openmc/core/listeners/JoinMessageListener.java
  src/main/java/fr/openmc/core/utils/customitems/CustomItemRegistry.java
  src/main/java/fr/openmc/core/utils/customitems/KebabItem.java
  src/main/java/fr/openmc/core/utils/messages/Prefix.java
Labels: :package: Features

#191 Fixing the friend's username when a player joins or quits.
  src/main/java/fr/openmc/core/listeners/JoinMessageListener.java
Labels: :lady_beetle: Bug Report

#192 Fix chunk data loading and improve menu refresh handling
  src/main/java/fr/openmc/core/features/city/ChunkDataCache.java
  src/main/java/fr/openmc/core/features/city/commands/CityCommands.java
  src/main/java/fr/openmc/core/features/city/menu/CityChunkMenu.java
  src/main/java/fr/openmc/core/features/homes/command/RelocateHome.java
  src/main/java/fr/openmc/core/features/homes/utils/HomeUtil.java
  src/main/java/fr/openmc/core/utils/ChunkInfo.java
  src/main/java/fr/openmc/core/utils/ChunkPos.java
  src/main/java/fr/openmc/core/utils/WorldGuardApi.java
Labels: 🆙 Amélioration

#190 Tablist
  build.gradle
  src/main/java/fr/openmc/core/OMCPlugin.java
  src/main/java/fr/openmc/core/features/scoreboards/GlobalTeamManager.java
  src/main/java/fr/openmc/core/features/scoreboards/ScoreboardManager.java
  src/main/java/fr/openmc/core/features/scoreboards/TabList.java
  src/main/java/fr/openmc/core/listeners/JoinMessageListener.java
  src/main/resources/plugin.yml
Labels: :package: Features, 🆙 Amélioration

#194 fix: if server started before 2AM, interest would be skipped that day + /wiki
  src/main/java/fr/openmc/core/commands/utils/Socials.java
  src/main/java/fr/openmc/core/features/economy/BankManager.java
  src/main/resources/config.yml
Labels: :sparkles: Fixes

#193 Mascot correctifs
  src/main/java/fr/openmc/core/OMCPlugin.java
  src/main/java/fr/openmc/core/features/city/CityManager.java
  src/main/java/fr/openmc/core/features/city/CityMessages.java
  src/main/java/fr/openmc/core/features/city/commands/AdminCityCommands.java
  src/main/java/fr/openmc/core/features/city/commands/CityCommands.java
  src/main/java/fr/openmc/core/features/city/mascots/Mascot.java
  src/main/java/fr/openmc/core/features/city/mascots/MascotUtils.java
  src/main/java/fr/openmc/core/features/city/mascots/MascotsListener.java
  src/main/java/fr/openmc/core/features/city/mascots/MascotsManager.java
  src/main/java/fr/openmc/core/features/city/menu/CityChunkMenu.java
  src/main/java/fr/openmc/core/features/city/menu/CityMenu.java
  src/main/java/fr/openmc/core/features/city/menu/CityTypeMenu.java
  src/main/java/fr/openmc/core/features/city/menu/mascots/MascotMenu.java
  src/main/java/fr/openmc/core/features/city/menu/mascots/MascotsSkinMenu.java
Labels: :sparkles: Fixes, 🆙 Amélioration

#207 Fix/menu state
  src/main/java/fr/openmc/core/features/city/commands/CityCommands.java
  src/main/java/fr/openmc/core/features/city/menu/CityMenu.java
Labels: :sparkles: Fixes, 🆙 Amélioration

#206 Fix des commandes admin des Contests
  src/main/java/fr/openmc/core/features/contest/commands/ContestCommand.java
  src/main/java/fr/openmc/core/features/contest/managers/ContestManager.java
Labels: :sparkles: Fixes

#222 Changement du lien vers le discord
  src/main/resources/config.yml
Labels: :arrows_counterclockwise: Changement

#237 Fix bug when deleting city
  src/main/java/fr/openmc/core/features/city/CityManager.java
Labels: :sparkles: Fixes, :warning: Urgent

#236 Fix et Improvement de ProtectionListener
  src/main/java/fr/openmc/core/features/city/CityManager.java
  src/main/java/fr/openmc/core/features/city/listeners/ProtectionListener.java
Labels: :sparkles: Fixes, :arrows_counterclockwise: Changement, :warning: Urgent

#248 fix: List.of() creates immutable list
  src/main/java/fr/openmc/core/features/city/commands/CityCommands.java
Labels: :sparkles: Fixes

#249 Ajout du son lors d'une mention dans le chat
  src/main/java/fr/openmc/core/listeners/AsyncChatListener.java
Labels: 🆙 Amélioration

#252 Réparation du freeze
  src/main/java/fr/openmc/core/utils/freeze/FreezeListener.java
  src/main/java/fr/openmc/core/utils/freeze/FreezeManager.java
Labels: :sparkles: Fixes

#256 Ajout du pourcentage pour sleep
  src/main/java/fr/openmc/core/CommandsManager.java
  src/main/java/fr/openmc/core/ListenersManager.java
  src/main/java/fr/openmc/core/OMCPlugin.java
  src/main/java/fr/openmc/core/features/city/CityManager.java
  src/main/java/fr/openmc/core/features/contest/managers/ContestManager.java
  src/main/java/fr/openmc/core/features/economy/BankManager.java
  src/main/java/fr/openmc/core/features/economy/EconomyManager.java
  src/main/java/fr/openmc/core/features/friend/FriendManager.java
  src/main/java/fr/openmc/core/features/homes/HomesManager.java
  src/main/java/fr/openmc/core/features/scoreboards/ScoreboardManager.java
  src/main/java/fr/openmc/core/features/tpa/TPAManager.java
  src/main/java/fr/openmc/core/listeners/SleepListener.java
  src/main/java/fr/openmc/core/utils/customitems/CustomItemRegistry.java
Labels: :package: Features

#253 Better Messages Click
  src/main/java/fr/openmc/core/features/city/commands/CityCommands.java
  src/main/java/fr/openmc/core/features/tpa/commands/TPACommand.java
Labels: :arrows_counterclockwise: Changement

#255 Change interest to 3% a 1%
  src/main/java/fr/openmc/core/features/city/City.java
  src/main/java/fr/openmc/core/features/economy/BankManager.java
Labels: :arrows_counterclockwise: Changement

#250 Fix Aywenite Block posed on/in mascotte
  src/main/java/fr/openmc/core/features/city/listeners/ProtectionListener.java
  src/main/java/fr/openmc/core/features/city/mascots/MascotsListener.java
  src/main/java/fr/openmc/core/features/city/menu/CityChunkMenu.java
  src/main/java/fr/openmc/core/features/friend/FriendSQLManager.java
Labels: :sparkles: Fixes

#246 fix issue #228
  src/main/java/fr/openmc/core/features/city/commands/CityCommands.java
  src/main/java/fr/openmc/core/features/city/menu/NoCityMenu.java
Labels: :sparkles: Fixes

#260 Ajout du RTP
  src/main/java/fr/openmc/core/CommandsManager.java
  src/main/java/fr/openmc/core/commands/utils/Rtp.java
  src/main/resources/data/rtp.yml
Labels: :package: Features

#273 Resolution bug detection ville
  src/main/java/fr/openmc/core/features/city/conditions/CityClaimCondition.java
  src/main/java/fr/openmc/core/features/city/listeners/ProtectionListener.java
  src/main/java/fr/openmc/core/features/scoreboards/ScoreboardManager.java
Labels: :sparkles: Fixes

#283 Adminshop
  src/main/java/fr/openmc/core/CommandsManager.java
  src/main/java/fr/openmc/core/OMCPlugin.java
  src/main/java/fr/openmc/core/features/adminshop/AdminShopCommand.java
  src/main/java/fr/openmc/core/features/adminshop/AdminShopManager.java
  src/main/java/fr/openmc/core/features/adminshop/AdminShopUtils.java
  src/main/java/fr/openmc/core/features/adminshop/AdminShopYAML.java
  src/main/java/fr/openmc/core/features/adminshop/ShopCategory.java
  src/main/java/fr/openmc/core/features/adminshop/ShopItem.java
  src/main/java/fr/openmc/core/features/adminshop/menus/AdminShopCategoryMenu.java
  src/main/java/fr/openmc/core/features/adminshop/menus/AdminShopMenu.java
  src/main/java/fr/openmc/core/features/adminshop/menus/ColorVariantsMenu.java
  src/main/java/fr/openmc/core/features/adminshop/menus/ConfirmMenu.java
  src/main/java/fr/openmc/core/utils/customitems/CustomItemRegistry.java
  src/main/java/fr/openmc/core/utils/customitems/buttons/MinusButton.java
  src/main/java/fr/openmc/core/utils/customitems/buttons/OneButton.java
  src/main/java/fr/openmc/core/utils/customitems/buttons/PlusButton.java
  src/main/java/fr/openmc/core/utils/customitems/buttons/StackButton.java
  src/main/java/fr/openmc/core/utils/messages/Prefix.java
  src/main/resources/data/adminshop.yml
Labels: :package: Features

#295 Changements mascottes
  src/main/java/fr/openmc/core/features/city/commands/CityCommands.java
  src/main/java/fr/openmc/core/features/city/mascots/MascotsListener.java
  src/main/java/fr/openmc/core/features/city/mascots/MascotsManager.java
  src/main/java/fr/openmc/core/features/city/menu/CityMenu.java
  src/main/java/fr/openmc/core/features/city/menu/mascots/MascotMenu.java
Labels: :sparkles: Fixes

#294 Patch interaction claims
  src/main/java/fr/openmc/core/features/city/listeners/ProtectionListener.java
Labels: :sparkles: Fixes

#293 Fix le message des restricition des villes si le joueur a pas de status
  src/main/java/fr/openmc/core/features/city/commands/CityCommands.java
  src/main/java/fr/openmc/core/features/city/conditions/CityTypeConditions.java
  src/main/java/fr/openmc/core/features/city/menu/CityMenu.java
Labels: :sparkles: Fixes

#296 Modif city chat
  src/main/java/fr/openmc/core/features/city/CityChatManager.java
  src/main/java/fr/openmc/core/features/city/CityManager.java
  src/main/java/fr/openmc/core/features/city/commands/CityChatCommand.java
  src/main/java/fr/openmc/core/features/city/listeners/CityChatListener.java
Labels: 🆙 Amélioration

#305 Fix bug de la quête "le randonneur"
  src/main/java/fr/openmc/core/features/quests/quests/WalkQuests.java
Labels: :sparkles: Fixes

#286 Amélioration des Claims des Villes
  src/main/java/fr/openmc/core/features/city/commands/CityCommands.java
  src/main/java/fr/openmc/core/features/city/listeners/ProtectionListener.java
  src/main/java/fr/openmc/core/features/city/mascots/MascotsListener.java
  src/main/java/fr/openmc/core/features/city/mascots/MascotsManager.java
  src/main/java/fr/openmc/core/utils/InputUtils.java
Labels: :sparkles: Fixes, 🆙 Amélioration

#307 Fix le formatage de l'argent limité
  src/main/java/fr/openmc/core/features/city/CityMessages.java
  src/main/java/fr/openmc/core/features/economy/EconomyManager.java
Labels: :sparkles: Fixes

#277 Ajout du leaderboard
  src/main/java/fr/openmc/core/OMCPlugin.java
  src/main/java/fr/openmc/core/features/leaderboards/LeaderboardManager.java
  src/main/java/fr/openmc/core/features/leaderboards/Utils/PacketUtils.java
  src/main/java/fr/openmc/core/features/leaderboards/commands/LeaderboardCommands.java
  src/main/java/fr/openmc/core/features/leaderboards/listeners/LeaderboardListener.java
  src/main/resources/data/leaderboards.yml
Labels: :package: Features

#266 Supprimer 40% des revenues de la personne quand elle meurs
  src/main/java/fr/openmc/core/ListenersManager.java
  src/main/java/fr/openmc/core/features/city/commands/CityCommands.java
  src/main/java/fr/openmc/core/listeners/PlayerDeadListener.java
Labels: :package: Features

#317 Patch rinding mascot
  src/main/java/fr/openmc/core/features/city/mascots/MascotsListener.java
  src/main/java/fr/openmc/core/features/city/mascots/MascotsManager.java
Labels: :sparkles: Fixes

#322 Possibilité de tpa plusieurs personnes
  src/main/java/fr/openmc/core/features/tpa/TPAQueue.java
  src/main/java/fr/openmc/core/features/tpa/commands/TPACommand.java
  src/main/java/fr/openmc/core/features/tpa/commands/TPAcceptCommand.java
  src/main/java/fr/openmc/core/features/tpa/commands/TPCancelCommand.java
  src/main/java/fr/openmc/core/features/tpa/commands/TPDenyCommand.java
Labels: :sparkles: Fixes

#325 Fix les quests dans les regions worldguard
  src/main/java/fr/openmc/core/features/quests/quests/BreakDiamondQuest.java
  src/main/java/fr/openmc/core/features/quests/quests/BreakStoneQuest.java
  src/main/java/fr/openmc/core/features/quests/quests/CityCreateQuest.java
  src/main/java/fr/openmc/core/features/quests/quests/ConsumeKebabQuest.java
  src/main/java/fr/openmc/core/features/quests/quests/CraftCakeQuest.java
  src/main/java/fr/openmc/core/features/quests/quests/CraftDiamondArmorQuest.java
  src/main/java/fr/openmc/core/features/quests/quests/CraftKebabQuest.java
  src/main/java/fr/openmc/core/features/quests/quests/EnchantFirstItemQuest.java
  src/main/java/fr/openmc/core/features/quests/quests/KillPlayersQuest.java
  src/main/java/fr/openmc/core/features/quests/quests/KillSuperCreeperQuest.java
  src/main/java/fr/openmc/core/features/quests/quests/KillZombieQuest.java
  src/main/java/fr/openmc/core/features/quests/quests/MineAyweniteQuest.java
  src/main/java/fr/openmc/core/features/quests/quests/SaveTheEarthQuest.java
  src/main/java/fr/openmc/core/features/quests/quests/SmeltIronQuest.java
  src/main/java/fr/openmc/core/features/quests/quests/WalkQuests.java
Labels: :sparkles: Fixes

#326 Fix opening mailbox menu when clicking on a chest
  src/main/java/fr/openmc/core/features/mailboxes/MailboxListener.java
Labels: :sparkles: Fixes

#327 Fix des petits bugs de ProtectionListener
  src/main/java/fr/openmc/core/features/city/listeners/ProtectionListener.java
Labels: :sparkles: Fixes

#328 Fix le bug de duplication dans le ChestMenu
  src/main/java/fr/openmc/core/features/city/listeners/ChestMenuListener.java
Labels: :sparkles: Fixes

#335 Faire en sorte que les joueurs puissent se prendre des dégâts dans leurs propres villes
  src/main/java/fr/openmc/core/features/city/listeners/ProtectionListener.java
Labels: :sparkles: Fixes

#319 [CHANGE] Messages on city create + Permission
  src/main/java/fr/openmc/core/features/city/commands/CityCommands.java
  src/main/java/fr/openmc/core/features/contest/commands/ContestCommand.java
  src/main/java/fr/openmc/core/features/mailboxes/MailboxCommand.java
  src/main/java/fr/openmc/core/features/tpa/commands/TPACommand.java
  src/main/java/fr/openmc/core/features/tpa/commands/TPAcceptCommand.java
  src/main/java/fr/openmc/core/features/tpa/commands/TPCancelCommand.java
  src/main/java/fr/openmc/core/features/tpa/commands/TPDenyCommand.java
Labels: :arrows_counterclockwise: Changement

#332 Fix du chargement des banques des villes
  src/main/java/fr/openmc/core/features/city/City.java
Labels: :sparkles: Fixes

#320 Ajout du /admcity claim bypass
  src/main/java/fr/openmc/core/features/city/commands/AdminCityCommands.java
  src/main/java/fr/openmc/core/features/city/listeners/ProtectionListener.java
  src/main/java/fr/openmc/core/utils/InputUtils.java
Labels: :package: Features, :arrows_counterclockwise: Changement

#339 Ajout d'un Debug pour tenter d'avoir l'erreur
  src/main/java/fr/openmc/core/listeners/UserUnloadListener.java
  src/main/java/fr/openmc/core/utils/LuckPermsAPI.java
Labels: :sparkles: Fixes

#278 Refonte de la Pipeline CI/CD
  .github/pull_request_template.md
  .github/release.yml
  .github/workflows/build-test.yml
  .github/workflows/check-milestone.yml
  .github/workflows/main.yml
  .github/workflows/milestone-close.yml
  .github/workflows/release-to-discord.yml
  .github/workflows/tests.yml
  build.gradle
  src/main/java/fr/openmc/core/CommandsManager.java
  src/main/java/fr/openmc/core/commands/utils/Restart.java
  src/main/java/fr/openmc/core/features/economy/EconomyManager.java
  src/main/java/fr/openmc/core/listeners/JoinMessageListener.java
  src/main/resources/plugin.yml
  src/test/resources/plugin.yml
Labels: :package: Features

#345 Fix quand on perds de l'argent
  src/main/java/fr/openmc/core/listeners/PlayerDeadListener.java
Labels: :sparkles: Fixes

#346 feat: add tag sync
  .github/workflows/tag-sync.yml
Labels: :arrows_counterclockwise: Changement

#348 Fix et ajout dans les Contests
  src/main/java/fr/openmc/core/features/contest/managers/ContestManager.java
Labels: :sparkles: Fixes, 🆙 Amélioration

#351 Fix l'envoi double du message d'avertissement quand on clique sur un bloc
  src/main/java/fr/openmc/core/features/city/listeners/ProtectionListener.java
Labels: :sparkles: Fixes

#350 Amélioration sur la commande /omcrestart
  src/main/java/fr/openmc/core/commands/utils/Restart.java
  src/main/java/fr/openmc/core/features/city/listeners/ChestMenuListener.java
  src/main/java/fr/openmc/core/features/city/menu/ChestMenu.java
  src/main/java/fr/openmc/core/features/scoreboards/ScoreboardManager.java
Labels: 🆙 Amélioration

#186 1.21.5 Update
  build.gradle
  src/main/java/fr/openmc/core/ListenersManager.java
  src/main/java/fr/openmc/core/listeners/DisableCreakings.java
  src/main/resources/data/motd.yml
  src/main/resources/plugin.yml
  src/test/resources/plugin.yml
Labels: :video_game: Game Update

#358 Fix des entités montables dans les claims
  src/main/java/fr/openmc/core/features/city/listeners/ProtectionListener.java
Labels: :sparkles: Fixes

#359 Fix AdminShop & Update
  src/main/java/fr/openmc/core/features/adminshop/AdminShopManager.java
  src/main/java/fr/openmc/core/features/adminshop/menus/ConfirmMenu.java
  src/main/resources/data/adminshop.yml
Labels: :sparkles: Fixes, 🆙 Amélioration
