Repository ServerOpenMC/PluginV2, pull requests merged in 2025-10, with the labels that each got.

#859 Fix du Discord Embed lors du release
  .github/release.yml
Labels: :arrows_counterclockwise: Changement

#858 Amélioration sur les homes
  src/main/java/fr/openmc/core/OMCPlugin.java
  src/main/java/fr/openmc/core/features/homes/HomesManager.java
  src/main/java/fr/openmc/core/features/homes/command/DelHomeCommand.java
  src/main/java/fr/openmc/core/features/homes/command/HomeWorldCommand.java
  src/main/java/fr/openmc/core/features/homes/command/RelocateHomeCommand.java
  src/main/java/fr/openmc/core/features/homes/command/RenameHomeCommand.java
  src/main/java/fr/openmc/core/features/homes/command/SetHomeCommand.java
  src/main/java/fr/openmc/core/features/homes/command/TpHomeCommand.java
  src/main/java/fr/openmc/core/features/homes/command/UpgradeHomeCommand.java
  src/main/java/fr/openmc/core/features/homes/icons/CachedIconItem.java
  src/main/java/fr/openmc/core/features/homes/icons/HomeIcon.java
  src/main/java/fr/openmc/core/features/homes/icons/HomeIconCacheManager.java
  src/main/java/fr/openmc/core/features/homes/icons/HomeIconRegistry.java
  src/main/java/fr/openmc/core/features/homes/icons/IconCategory.java
  src/main/java/fr/openmc/core/features/homes/icons/IconType.java
  src/main/java/fr/openmc/core/features/homes/icons/LegacyHomeIcon.java
  src/main/java/fr/openmc/core/features/homes/menu/HomeChangeIconMenu.java
  src/main/java/fr/openmc/core/features/homes/menu/HomeConfigMenu.java
  src/main/java/fr/openmc/core/features/homes/menu/HomeDeleteConfirmMenu.java
  src/main/java/fr/openmc/core/features/homes/menu/HomeMenu.java
  src/main/java/fr/openmc/core/features/homes/models/Home.java
  src/main/java/fr/openmc/core/features/homes/utils/HomeUtil.java
  src/main/java/fr/openmc/core/features/homes/world/DisabledWorldHome.java
  src/main/java/fr/openmc/core/features/mainmenu/menus/Page1.java
Labels: :sparkles: Fixes, 🆙 Amélioration, ⚡Optimisation

#864 Jouer l'animation de spawn que si le joueur est sur le sol
  src/main/java/fr/openmc/core/features/animations/listeners/PlayerFinishJoiningListener.java
Labels: :arrows_counterclockwise: Changement

#861 Fix de l'Aywen Cap Night Vision
  src/main/java/fr/openmc/core/listeners/AywenCapListener.java
Labels: :sparkles: Fixes

#868 Correctif du RTP
  src/main/java/fr/openmc/core/commands/utils/RTPCommands.java
Labels: :sparkles: Fixes

#873 Correctif du city details et des maires
  src/main/java/fr/openmc/core/features/city/actions/CityCreateAction.java
  src/main/java/fr/openmc/core/features/city/menu/list/CityListDetailsMenu.java
  src/main/java/fr/openmc/core/features/city/menu/list/CityPlayerListMenu.java
Labels: :sparkles: Fixes

#870 Tentative de Correctif sur la corruption du fichier yml des Contests
  src/main/java/fr/openmc/core/features/contest/managers/TradeYMLManager.java
  src/main/java/fr/openmc/core/utils/YmlUtils.java
Labels: :sparkles: Fixes

#867 Correctif du ErrorHandler
  src/main/java/fr/openmc/core/utils/errors/ErrorReporter.java
Labels: :sparkles: Fixes
