Repository ServerOpenMC/PluginV2, pull requests merged in 2025-08, with the labels that each got.

#687 Correctif sur les Trades des Contests
  src/main/java/fr/openmc/core/utils/ItemUtils.java
Labels: :sparkles: Fixes

#688 Changement dans les classements des contributeurs
  src/main/java/fr/openmc/core/features/leaderboards/ContributorStats.java
  src/main/java/fr/openmc/core/features/leaderboards/LeaderboardManager.java
Labels: 🆙 Amélioration

#689 Ajout du settings de suppresion des sons des Mascottes + Correctif de l'affichage de la vie des Mascottes
  src/main/java/fr/openmc/core/features/city/sub/mascots/MascotsManager.java
  src/main/java/fr/openmc/core/features/city/sub/mascots/listeners/MascotsSoundListener.java
  src/main/java/fr/openmc/core/features/settings/SettingType.java
Labels: :sparkles: Fixes, 🆙 Amélioration

#710 Fix mooshroom sound
  src/main/java/fr/openmc/core/features/city/sub/mascots/listeners/MascotsSoundListener.java
  src/main/java/fr/openmc/core/features/city/sub/mascots/models/Mascot.java
Labels: :sparkles: Fixes

#717 Rewrite des Contests + Ajout de nouveaux trades
  src/main/java/fr/openmc/api/menulib/default_menu/ConfirmMenu.java
  src/main/java/fr/openmc/core/features/contest/ContestEndEvent.java
  src/main/java/fr/openmc/core/features/contest/commands/ContestCommand.java
  src/main/java/fr/openmc/core/features/contest/listeners/ContestIntractEvents.java
  src/main/java/fr/openmc/core/features/contest/listeners/ContestListener.java
  src/main/java/fr/openmc/core/features/contest/managers/ContestManager.java
  src/main/java/fr/openmc/core/features/contest/managers/ContestPlayerManager.java
  src/main/java/fr/openmc/core/features/contest/managers/TradeYMLManager.java
  src/main/java/fr/openmc/core/features/contest/menu/ConfirmMenu.java
  src/main/java/fr/openmc/core/features/contest/menu/ContributionMenu.java
  src/main/java/fr/openmc/core/features/contest/menu/TradeMenu.java
  src/main/java/fr/openmc/core/features/contest/menu/VoteMenu.java
  src/main/java/fr/openmc/core/features/displays/scoreboards/ScoreboardManager.java
  src/main/java/fr/openmc/core/utils/ItemUtils.java
  src/main/resources/data/contest.yml
Labels: 🆙 Amélioration, ⚡Optimisation
